[tool.poetry]
name = "first-project"
version = "0.1.0"
description = ""
authors = ["ythomine"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
